name: Concatenate Source and Readme

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Concatenate Files
      run: |
        cd ${{ github.workspace }}
        find . -name '*.m' -o -name '*.md' | while read -r file; do
          echo "$file" >> all_source.txt
          cat "$file" >> all_source.txt
          echo >> all_source.txt
        done

    - name: Setup Git  
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
      
    - name: Commit Files
      run: |
        git checkout -B gh-pages
        git rm -rf .
        git checkout main -- README.md  # Explicitly checkout the latest README.md from main
        git add README.md all_source.txt
        git commit -m "Updating all source and README"

    - name: Push Changes
      uses: ad-m/github-push-action@v0.6 # Use a specific version instead of master for stability
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
