
name: Concatentate Source and Readme

on: 
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    
    - name: Concatenate Files
      run: |
        cd ${{ github.workspace }}
        find . -name '*.m' -o -name '*.md' | while read -r file; do
          echo "$file" >> all_source.txt
          cat "$file" >> all_source.txt
          echo >> all_source.txt
        done

    - name: Setup Git  
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      
    - name: Copy README
      run: |
        cp README.md ./README.md

    - name: Commit Files
      run: |
        git checkout -b gh-pages
        git rm -rf .
        git add README.md
        git add all_source.txt
        git commit -m "Updating all source file"
        
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
